---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: k8s-gateway
  namespace: flux-system
spec:
  interval: 30m

  chartRef:
    kind: OCIRepository
    name: k8s-gateway
    namespace: flux-system

  targetNamespace: k8s-gateway

  install:
    createNamespace: true

  values:
    domain: home.arpa

    ttl: 300

    watchedResources:
      - Ingress

    service:
      type: ClusterIP
      port: 53
      useTcp: true
