apiVersion: v1
kind: Secret
metadata:
    name: forgejo-runtime
    namespace: forgejo
type: Opaque
stringData:
    secret_key: ENC[AES256_GCM,data:l1vvSaxGMMGxEXgApZo+NgCcRuEhZvc4xEm9lCxi2bqKUq1TKYFA8YGvQftIsQsrUCKTiRNrjtToH0Np706SwA==,iv:siyhoU1nxSX8tU5UgGRUMK2+PXIR7GrJ0lcoFOGYOjs=,tag:B1hznNlOCoNilmCYsz3W6w==,type:str]
    internal_token: ENC[AES256_GCM,data:UUsYIV3PhWTwSCg83BPwJO7Npf/WR0jOL2IxFHEJVbZnc5bmdfzsu2reKUm/rEPNo5OkA0SzoTJzVDv/Z5FhcQ==,iv:BdyfESQvBQs8NMHt3M1nFbBC+25ez6iNogIuZ0FNSTA=,tag:cX3VT7RHeSnROJON28n3uw==,type:str]
    oauth2_jwt_secret: ENC[AES256_GCM,data:DsJS+hYAVEsMbMxhUmXIA7anrrjR1BD4uF+G7Lcj0M5ds6fzwZX2u8kKzg==,iv:Ea5OELco8cJGwT3pkUwHofP+0hpCGnZIxkiD4xZjSuA=,tag:cOJyKYPb05Umy1+x8SjQOA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzeG9aSDMvUmtLWkl4L0hG
            Uklmckp6RTNma2phSkN6N2lzbUVZRjdPOTNrCmJaZTk1bGlNdHNWTENHV0dyQmFI
            Zzk4a1R4TVlFRjZ0NlBvcUptUVZxVEkKLS0tIEExMllhVFRmakgvSHZoVnB3RHNZ
            a0FwNGM5YkxDS3U5S2lrNEJsWjF0MXMKmKclWN0WAmXaBu9+rLyyb5f2Y9QFPkEx
            bETv88wVE0cxg7rReqVGhzeYLJZVtjG/W/A6v047c0KyVdkB3pWKHw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rlnjsjr23hwvnev6ld98hsv55s3dlr60psvcrs3k08puxgyaysfq9kkh0d
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T12:47:08Z"
    mac: ENC[AES256_GCM,data:1plm66ZKcrYmeXOtSQMH7M4++oEUWB/gaG3n/i+ggs57Pm+Z2geH92xA9RJi7OpWnsPHOvPAECu9bL5K3N9wLlLoVftHsxrOnCnlbeMHmIRV2l7kt3jDk0uwDdyjHCjhC8AyxxSHSkvelpDg7oj6y+G4W+DfxENwuBCFrstGHuM=,iv:/qssYiyFPIhgJWG4il85utvVps/+68WG8/P9lI59Fqc=,tag:q0IspW6IKYzK4UwZbIEN7w==,type:str]
    version: 3.13.3
