apiVersion: v1
kind: Secret
metadata:
    name: forgejo-tls
    namespace: forgejo
type: kubernetes.io/tls
stringData:
    tls.crt: ENC[AES256_GCM,data:ifySkhoKuEtGa7qA1A/jvRofsj1dAlOC988Yi+9Mjwagz8wY8dWIuSI9+gNLY/NDydF0L2cMg4JFfVcpETiXIrE8pRwZjk2TgT6NQfKQhWZ3hFKt6CA1/VdTvTlZ95s1fHMyk4jNdj5sqKMBeyP2Xz6CXA0qx6ume2Tqzz4le37NpMeX34GwpWnOGtibZNQSCDOr4tZnEc0ZnI2tAOH5GSRWQz3oH7gGCZ8Vux0t4q4puevhVWzZbGm9kLxYr4aKzI5U84mcNU4de8uMuDy7Ll4fdujgm3fQIn8+vY88JEQrJG8YIeYqkfZVuzEJuE+ynZ+CdRFLBS7yRcaKmrLNoxf8XY0oVkJp0PDGE+k5oCNpeq/Cl2snmqgbeJ4KZQXrfJbQF0FY5Wbu6E3hjN983/0gLHxZQqLDO4QWmai+HlpS2xWRXv47f7thEKFGANupzleQMIeQhg3jKvaihmrpuMewHx4peEIiKEa6wfGgdooeN/Ng0CK2YSZ3jepGDE3bP943TlMCn3YkiUXqbaR91VNxTp0DGRCb0b+mlNAKACpe1c3AbPKx2r/a8tUdJvvPjB+6Ns7o5VexjpL3BgeUKb6c3Y7bw+0HRd/DMKXAfwnDsgOdDAnD0lph8SFgmsPNjW9Mqrpd/c9CEfyz7Pi0VNjdWAtHeRGgZn7wT5ZW0L9Gs2We5NpRz62l5B5xNZKVKA39y0Qb0RGg/b5721ZBdCtvb3nS4+jv5qPuCL1ks3X4cSEIsilxFq6LjLzPGImPdsFR8G8O1fUZrjOhhDV9bMa6uJ4TdhvRHBedlYiVYggauyi59M1a79N88884HsKJlpiq+HKNOyYw9gTiRM48TZjZad6xQhKNkw2h2toiDI3uD8fFdRPxUmLGlds7TULGZa0xCZCyaC5/VMkwxcyLWyUCRk7vW2U6,iv:oCFhCkf8k17NBpizyslTHcFJ1hkFwselV9DxYgjhEyA=,tag:fkxvJBq1dGFlATgXg10qWQ==,type:str]
    tls.key: ENC[AES256_GCM,data:lOqWtMKLNPsciwNEd+pKfVuAuj34/XUkyB1lIc/Q3i7/DlUS9IPU+zoawFOKeUpFQvz3yKJcWP/O2mwTQ0yU9VTKeiAnBsiB42rsjjg4rNNowuTYtkMRolywSLoWM5zDogwPYp0lsQXxFVcf9fILQyKdRpnLGPIgAsBALLIxGRF1RFK5WTj2ip3IUiB3u7SIad23TwX7qwG2zv0z6BlAT6YK5edh5eCk/KnB0r+TNqy6eCkOB8VUfgsTmYcr8EpcO9EyckZohIKDfRy1PR47U7/heP71haH2ZJ8gzvtNCPSQcYyx1dnDOJQfQQjja/ecvg==,iv:hrITrDgZWtS2n9kYQIL806n5zSnSY5RPg9yrEI06Yic=,tag:N0ip3nqnJoXN1xO/XeXNbg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxZFczOUhoakNzYTBvb09G
            bFNLVzNJZ0w4ZUJON1U2YmRTUWE0N0Mxb1JJCjRYcW4zVEZsREVqWTF2clMvcHN1
            d2VKWVU1MTBaY283UWY2ZUgwUzVmd2MKLS0tIDBpNzg4bVMyY1M4bjVtUFl0TVFP
            Tk9zL05ucVp0bWo5U3lqazdEWmc3RGcKtwRYXIFLh3vg9C5MfyodSzG3fiH8OC0c
            E1X1jkONWOvNW0rKawqdaGdba4BQ/Uwd316OgrQQTObVDK4bOpZSiA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rlnjsjr23hwvnev6ld98hsv55s3dlr60psvcrs3k08puxgyaysfq9kkh0d
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T12:19:01Z"
    mac: ENC[AES256_GCM,data:S+j7z+4dM6bJluDhF9mdT0E6wEQB/qh3bxZY2u54lRK2eybLS62ocBn8D4O/byNbVTkiaqFg5JOddtIQyE/4DRJWCAq/SYwRNLm57BUwWufrrRErMq5Ow7ylACuC5+E/Vf+UeCKHYj5g6zHnc0fcHCswe+D7XIsZAtlEq/N5pRE=,iv:1xSI6xsC0Z+rfj+zYWZpOunYh5lxQ6OWGXLmChajNsI=,tag:HLMS9pFZKA4eKKZQHdsjig==,type:str]
    version: 3.13.3
