apiVersion: v1
kind: Secret
metadata:
    name: forgejo-runtime
    namespace: forgejo
type: Opaque
stringData:
    secret_key: ENC[AES256_GCM,data:Is83xj3fcpWUGDcXrPjBKyA6jkqHdGoLPCI0fsPMxOMP/cIuWTDBrMgxfF8cB5eutW7Hy9nACFkMW6U+gg1bsQ==,iv:mFQCearhBg4Cx1WMcnEkL6HZ6tOyZZaedPwB5Eav64w=,tag:6uChTdq0554Noip2Taq61Q==,type:str]
    internal_token: ENC[AES256_GCM,data:C+ESIoFBk15Cs7Cq/DI1E7ZrXLZ8+kCNwch0t59c5zIZHAN10u0hlsQVzF6CamkFu+5RXur5WfJpB8Dk98/8/A==,iv:k+2EYtG6WvQAzgQKaogFAxmrZ1LhYrkra91Dj6gtpQQ=,tag:9UEWXz7svpN0oRsTKY1O8g==,type:str]
    oauth2_jwt_secret: ENC[AES256_GCM,data:zEaCX9jQ2M7iuoXPdXgCFcxySo6VT5qdvnLyKj5/5IX6uVG6LeZQ7vl4UWU=,iv:JX86KPsyWihBsMpY6teHPu8Y075PvnFq8mP6QqMju98=,tag:u7B8UTVXJwjwAGsBUXhCIQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnVWI2cWlhdkF6TkIxVzhS
            ZW5xRGJmeDd3S0hEa1FlT3JMVE9teWg0bWtzCm5wOHNwVHAxRWp6d0wzT2FEK2FL
            dVI5L0tJU2ZoQld4eEMvc0dCVnVETVUKLS0tIDA2M25lZ3hLZnpzSU5rVExITi9q
            VU5rZFRzdjRXZHhtQ3FVdWtqanpJK1EKTGxPUSVjkmdZdf9Mvf3Id2fd2thUm4TE
            3eDhJXC2oUXay6VRGq3HL6yDSYx3vLDEWNVpzYCbn01QfOltvsl6UQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rlnjsjr23hwvnev6ld98hsv55s3dlr60psvcrs3k08puxgyaysfq9kkh0d
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T12:12:34Z"
    mac: ENC[AES256_GCM,data:i+Xhr2ARvaPKzSfmMOsDyuR5A3muQc8NNy+J/4GPaFj3nmjPFBwsnxaW6PkJHdtnr+9ywwtwzE589SsTTjY+k9gD8e3gDxPonCEjD3jjd8MHx6aDzw+8JHFLjzo/GTZu0dND0q3u2yUa9kAqGJGDS9iB6AQeVwoDxVuAyVHVaeQ=,iv:JgcJ+VXZ6IiRgzRzUJZeQxsXwUBjbkEBCGwBwq+96PA=,tag:p+ovd86m7QJ9Y0zRwU1Wag==,type:str]
    version: 3.13.3
